name: coselig_staff_portal
description: "coselig.com staff portal application"
publish_to: 'none'
version: 0.1.2+10

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  http: ^1.6.0
  provider: ^6.1.5+1
  excel: ^4.0.3
  intl: ^0.19.0
  universal_html: ^2.3.0
  flutter_blue_plus: ^1.32.8
  permission_handler: ^11.3.1
  url_strategy: ^0.2.0
  package_info_plus: ^8.1.2




dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0



flutter_launcher_icons:
  android: true
  ios: true
  image_path: "ctc_icon.png"


flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Iansui
      fonts:
        - asset: assets/fonts/Iansui-Regular.ttf
